substitutions:
  _USERNAME: "default_user" # Replace with your default username or set via build trigger
  _VM_INSTANCE: "instance-20241228-143729" # Updated VM instance name
  _VM_ZONE: "us-central1-b" # Replace with your VM zone or set via build trigger
  _VM_PATH: "/home/default_user/app" # Replace with your desired path on VM or set via build trigger
  _INSTANCE_CONNECTION_NAME: "your-project:us-central1:instance-20241228-143729" # Ensure this is correct
  _VPC_CONNECTOR: "projects/${PROJECT_ID}/locations/us-central1/connectors/cloud-run-vpc-connector" # Name of the VPC connector
  _DB_HOST: "${SUPABASE_DB_HOST}" # Updated to reference environment variable
  _DB_USER: "${SUPABASE_DB_USER}" # Updated to reference environment variable
  _DB_NAME: "${SUPABASE_DB_NAME}" # Updated to reference environment variable
  # Remove hardcoded DB_PASSWORD and use secrets
  _PROJECT_ID: "your-project-id" # Add your GCP project ID

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/gestionale:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/gestionale:$COMMIT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "gestionale"
      - "--image=gcr.io/${_PROJECT_ID}/gestionale:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--port=8080"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--timeout=300"
      - "--set-env-vars=PORT=8080"
      - "--set-env-vars=SUPABASE_DB_PORT=6543,SUPABASE_DB_NAME=postgres"
      - "--set-secrets=/run/secrets/supabase_password=supabase-db-password:latest"
      - "--allow-unauthenticated"
      - "--min-instances=1"
      - "--max-instances=10"
      - "--execution-environment=gen2"
      - "--vpc-connector=${_VPC_CONNECTOR}"
      - "--service-account=${_SERVICE_ACCOUNT}"
      - "--startup-probe-period=10s"
      - "--startup-probe-timeout=5s"
      - "--startup-probe-failure-threshold=5"
      - "--set-secrets"
      - >-
        SUPABASE_DB_PASSWORD=SUPABASE_DB_PASSWORD:latest,
        SUPABASE_DB_HOST=SUPABASE_DB_HOST:latest
      - "--set-env-vars"
      - >-
        SUPABASE_DB_PORT=6543,
        SUPABASE_DB_NAME=postgres,
        SUPABASE_DB_USER=postgres.nltoknxotsigtyrceuyt

  # Add firewall rule to allow TCP traffic on port 8080
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "firewall-rules"
      - "create"
      - "allow-8080"
      - "--allow=tcp:8080"
      - "--target-tags=allow-8080"
      - "--description=Allow incoming traffic on port 8080 for web application"
      - "--network=default"

images:
  - "gcr.io/${_PROJECT_ID}/gestionale:$COMMIT_SHA"
